# Generated by Django 3.2.12 on 2022-03-13 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default='1')),
                ('completed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('0', 'PENDING'), ('1', 'IN_PROGRESS'), ('2', 'COMPLETED'), ('3', 'CANCELLED')], default='0', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('0', 'PENDING'), ('1', 'IN_PROGRESS'), ('2', 'COMPLETED'), ('3', 'CANCELLED')], max_length=100, null=True)),
                ('new_status', models.CharField(choices=[('0', 'PENDING'), ('1', 'IN_PROGRESS'), ('2', 'COMPLETED'), ('3', 'CANCELLED')], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remainder_time', models.TimeField()),
                ('last_day', models.DateField(blank=True, default=None, null=True)),
                ('disabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
