# Generated by Django 4.0.1 on 2022-03-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.CharField(choices=[('0', 'PENDING'), ('1', 'IN_PROGRESS'), ('2', 'COMPLETED'), ('3', 'CANCELLED')], max_length=100),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='old_status',
            field=models.CharField(choices=[('0', 'PENDING'), ('1', 'IN_PROGRESS'), ('2', 'COMPLETED'), ('3', 'CANCELLED')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0', 'PENDING'), ('1', 'IN_PROGRESS'), ('2', 'COMPLETED'), ('3', 'CANCELLED')], default='0', max_length=100),
        ),
    ]
