# Generated by Django 4.0.1 on 2022-03-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='reminder_time',
            new_name='remainder_time',
        ),
    ]
