# Generated by Django 4.0.1 on 2022-03-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_reminder_time_report_remainder_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
