# Generated by Django 2.2.12 on 2022-02-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priortity',
            field=models.IntegerField(default='1'),
        ),
    ]
